spring:
  datasource:
    url: jdbc:mysql://sports-echo-mysql-instance.c8cvx8gfy4m3.ap-northeast-2.rds.amazonaws.com/echo_db
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

api:
  key: ${RAPID_API_KEY}

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
    region:
      static: ap-northeast-2
    stack:
      auto: false
    s3:
      bucket: sports-echo/scheduler